### ISSUE TITLE
Configuration Module 

### ISSUE THREAD

**Issue by LunatheCatBoss** [FarzaneHashemii/Pokemon#1]
Please get started creating the class branch1.Analysis.Analysis(analysis_config:str) and set up reading configuration files from given file path.

**Comment by FarzaneHashemii** [comment]
I renamed branch1 to module_code, loaded the config files within the __init__.py, and wrote simple configurations into the config yaml files. The contents of the yaml files must be edited at a later state, and my code must be tested. I will also revisit my code to catch errors and utilize logging in my written code.
