### ISSUE TITLE
Start working on loading data from API

### ISSUE THREAD

**Issue by LunatheCatBoss** [FarzaneHashemii/Pokemon#5]
Please start working on the following : 

load_data()
''' Retrieve data from the POKEMON API

This function makes an HTTPS request to the pokemon API and retrieves your selected data. The data is
stored in the Analysis object.

Parameters
----------
None

Returns
-------
None

'''

**Comment by LeotheCatDeveloper** [comment]
already started, we have a running initial code, very basic though at this stage
